<a href="https://colab.research.google.com/github/YoonHyeJu/project1/blob/master/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow import keras

In [2]:
# x는 28x28 픽셀의 각 손글씨 이미지 데이터
# y는 분류에 사용되는 0~9 사이의 레이블 값
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


11493376/11490434 [==============================] - 0s 0us/step


In [3]:
print(y_train.shape)

(60000,)


In [4]:
for i in range(5):
    print(y_train[i])

5
0
4
1
9


In [5]:
# one-hot encoding
# 5 -> [0,0,0,0,0,1,0,0,0,0]

y_train = keras.utils.to_categorical(y_train, 10) # 10: 클래스 몇개인지
y_test = keras.utils.to_categorical(y_test, 10)

In [6]:
for i in range(5):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [7]:
print(x_train.shape, x_test.shape) # 60000개의 이미지 데이터 , 28X28 픽셀로 이루어진!

(60000, 28, 28) (10000, 28, 28)


In [9]:
#뉴럴넷에 넣기 위해서는 매트릭스X, 쫙 펼쳐줘야됨

x_train = x_train.reshape(60000, 28*28)
x_test = x_test.reshape(10000, 28*28)

In [17]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [18]:
print(x_train[0])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255
 247 127   0   0   0   0   0   0   0   0   0   0   0   0  30  36  94 154
 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0   0   0
   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82
  82  56  39   0   0   0   0   0   0   0   0   0   0   0   0  18 219 253
 253 253 253 253 198 182 247 241   0   0   0   0   

In [11]:
model = keras.Sequential()
model.add(keras.layers.Dense(32, activation='sigmoid',input_shape = (28*28,)))
model.add(keras.layers.Dense(32, activation='sigmoid'))
model.add(keras.layers.Dense(10, activation='sigmoid')) # 10 <- y데이터의 갯수를 따름

In [12]:
optimizer = keras.optimizers.SGD(lr=0.1)
model.compile(optimizer=optimizer, loss = "categorical_crossentropy", metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                25120     
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                330       
Total params: 26,506
Trainable params: 26,506
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(x_train, y_train, batch_size=128, epochs = 10, validation_data=(x_test,y_test))
# epochs : 60000개의 전체 학습 데이터를 몇 번 반복해서 학습할지

Epoch 1/10
469/469 [==============================] - 2s 4ms/step - loss: 1.7388 - accuracy: 0.5699 - val_loss: 1.1113 - val_accuracy: 0.7512
Epoch 2/10
469/469 [==============================] - 2s 4ms/step - loss: 0.8897 - accuracy: 0.7846 - val_loss: 0.7116 - val_accuracy: 0.8300
Epoch 3/10
469/469 [==============================] - 2s 4ms/step - loss: 0.6639 - accuracy: 0.8257 - val_loss: 0.5948 - val_accuracy: 0.8492
Epoch 4/10
469/469 [==============================] - 2s 4ms/step - loss: 0.5994 - accuracy: 0.8332 - val_loss: 0.5615 - val_accuracy: 0.8369
Epoch 5/10
469/469 [==============================] - 2s 4ms/step - loss: 0.5474 - accuracy: 0.8443 - val_loss: 0.5337 - val_accuracy: 0.8470
Epoch 6/10
469/469 [==============================] - 2s 4ms/step - loss: 0.5135 - accuracy: 0.8491 - val_loss: 0.5080 - val_accuracy: 0.8553
Epoch 7/10
469/469 [==============================] - 2s 4ms/step - loss: 0.4936 - accuracy: 0.8535 - val_loss: 0.4825 - val_accuracy: 0.8670
Epoch 

In [14]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 0s 2ms/step - loss: 0.4326 - accuracy: 0.8669


[0.4325767159461975, 0.8669000267982483]

In [15]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.4326 - accuracy: 0.8669


[0.4325767159461975, 0.8669000267982483]

In [16]:
model.fit(x_train, y_train, batch_size=256, epochs = 10, validation_data=(x_test,y_test))
model.evaluate(x_test, y_test)

Epoch 1/10
235/235 [==============================] - 1s 5ms/step - loss: 0.4289 - accuracy: 0.8696 - val_loss: 0.4052 - val_accuracy: 0.8763
Epoch 2/10
235/235 [==============================] - 1s 5ms/step - loss: 0.3987 - accuracy: 0.8810 - val_loss: 0.4029 - val_accuracy: 0.8770
Epoch 3/10
235/235 [==============================] - 1s 5ms/step - loss: 0.3994 - accuracy: 0.8790 - val_loss: 0.4039 - val_accuracy: 0.8759
Epoch 4/10
235/235 [==============================] - 1s 5ms/step - loss: 0.3870 - accuracy: 0.8828 - val_loss: 0.3560 - val_accuracy: 0.8944
Epoch 5/10
235/235 [==============================] - 1s 5ms/step - loss: 0.3858 - accuracy: 0.8821 - val_loss: 0.3830 - val_accuracy: 0.8864
Epoch 6/10
235/235 [==============================] - 1s 5ms/step - loss: 0.3771 - accuracy: 0.8855 - val_loss: 0.3756 - val_accuracy: 0.8888
Epoch 7/10
235/235 [==============================] - 1s 5ms/step - loss: 0.3781 - accuracy: 0.8868 - val_loss: 0.3638 - val_accuracy: 0.8943
Epoch 

[0.34747496247291565, 0.8928999900817871]

방법 2 ( 방법1보다 정확도 더 높음 )

In [19]:
import tensorflow as tf

In [20]:
#MNIST 데이터셋 임포트
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [21]:
#데이터 전처리
x_train, x_test = x_train/255.0, x_test/255. #0~255 사이의 값을 0~1.0 사이로 만들기 위함

In [25]:
#모델 구성
# Sequential : 이전 layer의 output이 다음 layer의 input으로 들어가는 선형적인 경우
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(512, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
# Flatten : 28*28 데이터를 일차원으로 만들기 위함
# relu: 입력 값이 커질수록 어떤 경향을 보인다로 해석 가능 / 입력 값의 기울기는 어떤 경향을 보인다로 해석 가능
# Softmax: 3개 이상을 분류할 때 자주 사용
# Sigmoid: S형태, 모든 입력값이 증가함에 따라 결과값이 증가만 계속 되는..

In [26]:
#모델 컴파일
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
#optimizer: 학습속도를 빠르고 안정적이게 하기 위함.
#sparse_categorical_crossentropy: 다중 분류 손실함수, integer type

In [27]:
#모델 훈련
model.fit(x_train, y_train, epochs=5)
#epochs: 반복 횟수

Epoch 1/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.2008 - accuracy: 0.9413
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0814 - accuracy: 0.9752
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0535 - accuracy: 0.9833
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0369 - accuracy: 0.9884
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0270 - accuracy: 0.9914


In [28]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print('테스트 정확도:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0762 - accuracy: 0.9776
테스트 정확도: 0.9775999784469604


In [29]:
loss, accuracy = [], []
for i in range(10):
    model.fit(x_train, y_train, epochs=1)
    loss.append(model.evaluate(x_test, y_test)[0])
    accuracy.append(model.evaluate(x_test, y_test)[1])

print(accuracy)

313/313 [==============================] - 1s 2ms/step - loss: 0.0890 - accuracy: 0.9824
[0.9793000221252441, 0.9789999723434448, 0.9828000068664551, 0.982200026512146, 0.9805999994277954, 0.9812999963760376, 0.9804999828338623, 0.9800000190734863, 0.9807999730110168, 0.9824000000953674]
