<a href="https://colab.research.google.com/github/YoonHyeJu/project1/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
# 단일 객체
array = np.arange(0,10)
np.save('saved.npy', array)

In [6]:
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
#복수 객체
array1 = np.arange(0,10)
array2 = np.arange(10,20)
np.savez('saved.npz', array1=array1, array2=array2)

In [25]:
data = np.load('saved.npz')

In [27]:
data['array1']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
data['array2']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
data

In [30]:
#넘파이 원소 오름차순 정렬
array = np.array([5,1,3,6,9])
array.sort()
print(array)

[1 3 5 6 9]


In [33]:
#넘파이 원소 내림차순 정렬
print(array[::-1])

[9 6 5 3 1]


In [35]:
# 열을 기준으로 정렬
array = np.array([[5,8,2,4,1], [3,6,8,9,1]])
array.sort(axis=0)
print(array)
print(array[::-1])

[[3 6 2 4 1]
 [5 8 8 9 1]]
[[5 8 8 9 1]
 [3 6 2 4 1]]


In [36]:
#균일한 간격으로 데이터 생성
array = np.linspace(0,10,5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


In [38]:
#난수의 재연(실행마다 결과 동일)
np.random.seed(42)
print(np.random.randint(0,10,(2,3)))

[[6 3 7]
 [4 6 9]]


In [41]:
# 넘파이 배열 객체 복사
array1 = np.arange(0,10)
array2 = array1
array2[0] = 99
print(array1)

array1 = np.arange(0,10)
array2 = array1.copy()
array2[0] = 99
print(array1)

[99  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
